name: Build Documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: my-docs-builder:latest

    - name: Generate documentation
      run: |
        mkdir site
        docker run --rm -v $GITHUB_WORKSPACE:/home/appuser -v $GITHUB_WORKSPACE/site:/home/appuser/site my-docs-builder:latest

    - name: Archive documentation
      uses: actions/upload-pages-artifact@v1.0.9
      with:
        name: documentation
        path: site/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
